- README.md
- Added ruby style to snippets
> added ruby style to snippets in Readme

- README.md
- jwt_sessions.gemspec
- test/support/dummy_api/spec/controllers/refresh_controller_spec.rb
- test/support/dummy_sinatra_api/Gemfile
- test/support/dummy_sinatra_api/app.rb
ref https://github.com/tuwukee/jwt_sessions/issues/2
> Sinatra dummy API

- .travis.yml
- Gemfile
- README.md
- jwt_sessions.gemspec
- lib/jwt_sessions.rb
- lib/jwt_sessions/authorization.rb
- lib/jwt_sessions/session.rb
- lib/jwt_sessions/token.rb
- lib/jwt_sessions/version.rb
- test/units/jwt_sessions/test_session.rb
- test/units/jwt_sessions/test_token.rb
- test/units/test_jwt_sessions.rb
all validations are handled by ruby-jwt now, fixed README
> Added support for JWT options

- README.md
- lib/jwt_sessions.rb
- lib/jwt_sessions/authorization.rb
- lib/jwt_sessions/redis_token_store.rb
- lib/jwt_sessions/refresh_token.rb
- lib/jwt_sessions/session.rb
- test/support/dummy_api/app/controllers/login_with_cookies_controller.rb
- test/support/dummy_api/spec/controllers/login_with_cookies_controller_spec.rb
- test/support/dummy_api/spec/controllers/users_controller_spec.rb
- test/units/jwt_sessions/test_refresh_token.rb
- test/units/jwt_sessions/test_session.rb
Ref https://github.com/tuwukee/jwt_sessions/issues/7
Adds ability to flush specific sessions.
> Pre release

- README.md
- lib/jwt_sessions/access_token.rb
- lib/jwt_sessions/authorization.rb
- lib/jwt_sessions/session.rb
- test/support/dummy_api/app/controllers/refresh_by_access_controller.rb
- test/support/dummy_api/config/routes.rb
- test/support/dummy_api/spec/controllers/refresh_by_access_controller_spec.rb
- test/units/jwt_sessions/test_session.rb
Ref https://github.com/tuwukee/jwt_sessions/issues/18
> Link access to refresh

- lib/jwt_sessions/access_token.rb
- lib/jwt_sessions/errors.rb
- lib/jwt_sessions/session.rb
- lib/jwt_sessions/token.rb
- test/units/jwt_sessions/test_session.rb
- test/units/jwt_sessions/test_token.rb
Ref https://github.com/tuwukee/jwt_sessions/issues/23
> Extend error classes, add ability to flush access tokens

- .travis.yml
- Gemfile
- README.md
- lib/jwt_sessions.rb
- lib/jwt_sessions/rails_authorization.rb
- test/support/dummy_api/Gemfile
- test/support/dummy_api/app/channels/application_cable/channel.rb
- test/support/dummy_api/app/channels/application_cable/connection.rb
- test/support/dummy_api/app/controllers/application_controller.rb
- test/support/dummy_api/app/jobs/application_job.rb
- test/support/dummy_api/app/mailers/application_mailer.rb
- test/support/dummy_api/config/application.rb
- test/support/dummy_api/config/environments/development.rb
- test/support/dummy_api/config/environments/test.rb
- test/support/dummy_api/spec/rails_helper.rb
- Fix RailsAuthorization concern
- Cleanup Dummy Rails app (remove jobs, cables, etc.)
- Configure Dummy app to support both Rails 4 and 5
- Add Rails 4 testing to Travis
- Update Contributing section
> Fix Rails 4 compatibility

- .travis.yml
- lib/jwt_sessions/session.rb
- test/units/jwt_sessions/test_session.rb
ref https://github.com/tuwukee/jwt_sessions/issues/36 https://github.com/tuwukee/jwt_sessions/issues/35
> Sessions flow improvements

- lib/jwt_sessions/refresh_token.rb
- lib/jwt_sessions/store_adapters/abstract_store_adapter.rb
- lib/jwt_sessions/store_adapters/memory_store_adapter.rb
- lib/jwt_sessions/store_adapters/redis_store_adapter.rb
- test/units/jwt_sessions/store_adapters/test_memory_store_adapter.rb
- test/units/jwt_sessions/store_adapters/test_redis_store_adapter.rb
- test/units/jwt_sessions/test_session.rb
- test/units/test_token_store.rb
> Use named arguments, store refactoring

- README.md
- test/support/dummy_api/Gemfile
ref https://github.com/tuwukee/jwt_sessions/issues/50
> Add sessions options description to README

- README.md
- lib/jwt_sessions.rb
- lib/jwt_sessions/access_token.rb
- lib/jwt_sessions/refresh_token.rb
- lib/jwt_sessions/session.rb
- test/units/jwt_sessions/test_session.rb
ref https://github.com/tuwukee/jwt_sessions/issues/55
> Expiration on a session level

- lib/jwt_sessions/refresh_token.rb
- lib/jwt_sessions/session.rb
- lib/jwt_sessions/store_adapters/memory_store_adapter.rb
- lib/jwt_sessions/store_adapters/redis_store_adapter.rb
- test/units/jwt_sessions/test_refresh_token.rb
- test/units/jwt_sessions/test_session.rb
ref https://github.com/tuwukee/jwt_sessions/issues/61
> Fix namespaced lookup

- test/support/dummy_api/Gemfile
- test/support/dummy_api/app/controllers/login_controller.rb
- test/support/dummy_api/config/routes.rb
- test/support/dummy_api/spec/controllers/login_controller_spec.rb
> Add logout specs

- lib/jwt_sessions/token.rb
Discussed here https://github.com/tuwukee/jwt_sessions/issues/82
> replace symbol exp key with string one in meta

- jwt_sessions.gemspec
- lib/jwt_sessions.rb
> Update jwt to 2.2.3

- .github/workflows/main.yml
- CHANGELOG.md
- Gemfile
- README.md
- jwt_sessions.gemspec
- lib/jwt_sessions/store_adapters/redis_store_adapter.rb
- lib/jwt_sessions/version.rb
- test/support/dummy_api/Gemfile
- test/support/dummy_api/config/application.rb
- test/support/dummy_api/config/initializers/jwt_sessions.rb
- test/support/dummy_sinatra_api/Gemfile
- test/support/dummy_sinatra_api/app.rb
- test/support/dummy_sinatra_api/spec/spec_helper.rb
- test/units/jwt_sessions/store_adapters/test_redis_store_adapter.rb
Use Redis scan, add SSL params support to Redis storage adapter.
ref https://github.com/tuwukee/jwt_sessions/issues/97
ref https://github.com/tuwukee/jwt_sessions/issues/100
> Improve redis support

- lib/jwt_sessions/refresh_token.rb
- lib/jwt_sessions/store_adapters/redis_store_adapter.rb
Provide a namespace for namespaced refresh tokens on init.
ref https://github.com/tuwukee/jwt_sessions/issues/108
> Correctly init namespaced tokens from redis store

- CHANGELOG.md
- jwt_sessions.gemspec
- lib/jwt_sessions.rb
- lib/jwt_sessions/token.rb
- lib/jwt_sessions/version.rb
- test/units/jwt_sessions/test_token.rb
ref https://github.com/tuwukee/jwt_sessions/issues/113
> JWT default options updates

- lib/jwt_sessions/session.rb
- lib/jwt_sessions/store_adapters/redis_store_adapter.rb
- test/units/jwt_sessions/store_adapters/test_redis_store_adapter.rb
- test/units/jwt_sessions/test_session.rb
ref https://github.com/tuwukee/jwt_sessions/issues/115
> Do not pass nils into hmget/hmset

- CHANGELOG.md
- README.md
- jwt_sessions.gemspec
- lib/jwt_sessions/store_adapters/redis_store_adapter.rb
- lib/jwt_sessions/version.rb
- test/units/jwt_sessions/store_adapters/test_redis_store_adapter.rb
- test/units/jwt_sessions/test_token.rb
> Add redis pool size settings & Bump version

- CHANGELOG.md
- jwt_sessions.gemspec
- lib/jwt_sessions/store_adapters/redis_store_adapter.rb
- lib/jwt_sessions/version.rb
- test/units/jwt_sessions/store_adapters/test_redis_store_adapter.rb
ref https://github.com/tuwukee/jwt_sessions/issues/120
> Bump version & fix expire_at

- .github/workflows/main.yml
- CHANGELOG.md
- README.md
- jwt_sessions.gemspec
- lib/jwt_sessions.rb
- lib/jwt_sessions/version.rb
- test/support/dummy_api/config/initializers/jwt_sessions.rb
- test/support/dummy_sinatra_api/app.rb
- test/units/jwt_sessions/test_access_token.rb
- test/units/jwt_sessions/test_refresh_token.rb
- test/units/jwt_sessions/test_session.rb
- test/units/jwt_sessions/test_token.rb
- test/units/test_jwt_sessions.rb
ref https://github.com/tuwukee/jwt_sessions/issues/122
> Rename encryption key into signing key

- CHANGELOG.md
- README.md
- jwt_sessions.gemspec
- lib/jwt_sessions/store_adapters/redis_store_adapter.rb
- lib/jwt_sessions/version.rb
- test/units/jwt_sessions/test_session.rb
ref https://github.com/tuwukee/jwt_sessions/issues/126
ref https://github.com/tuwukee/jwt_sessions/issues/125
> Refresh token checks

- .github/workflows/main.yml
- CHANGELOG.md
- jwt_sessions.gemspec
- lib/jwt_sessions.rb
- lib/jwt_sessions/version.rb
- test/support/dummy_api/config/initializers/jwt_sessions.rb
ref https://github.com/tuwukee/jwt_sessions/issues/138
> Add jwt 2.9 support
